package dictionaryUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import dictionaryController.*;
import dictionaryData.Word;
import java.util.Collections;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author VuQuang
 */
public class DictionaryForm extends javax.swing.JFrame {
    
    public static final int MAX_WORDS = 150000;

    private DictionaryApp dict = new DictionaryApp();
    /**
     * Creates new form DictionaryForm
     */
    public DictionaryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelThongKe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableThongKe = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerDate1 = new javax.swing.JSpinner();
        jSpinnerDate2 = new javax.swing.JSpinner();
        jPanelManHinhChinh = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHienThiTu = new javax.swing.JTextArea();
        jTabbedPaneTraCuu = new javax.swing.JTabbedPane();
        jScrollPaneDSTu = new javax.swing.JScrollPane();
        jListDSTu = new javax.swing.JList<>();
        jScrollPaneDSYeuThich = new javax.swing.JScrollPane();
        jListDSYeuThich = new javax.swing.JList<>();
        jButtonDoiNgonNgu = new javax.swing.JButton();
        jLabelLang = new javax.swing.JLabel();
        jTextFieldTraCuu = new javax.swing.JTextField();
        jButtonThemYeuThich = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTuyChon = new javax.swing.JMenu();
        jMenuItemTraCuu = new javax.swing.JMenuItem();
        jMenuItemThongKe = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemThoat = new javax.swing.JMenuItem();

        jPanelThongKe.setPreferredSize(new java.awt.Dimension(678, 398));

        jLabel1.setText("Từ ngày");

        jLabel2.setText("Đến ngày");

        jTableThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Từ", "Số lần tra cứu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableThongKe);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("THỐNG KÊ TẦN SUẤT TRA CỨU TỪ");

        jSpinnerDate1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerDate1.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerDate1.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerDate1, "dd/MM/yyyy"));
        jSpinnerDate1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerDate1StateChanged(evt);
            }
        });

        jSpinnerDate2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerDate2.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerDate2.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerDate2, "dd/MM/yyyy"));
        jSpinnerDate2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerDate2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelThongKeLayout = new javax.swing.GroupLayout(jPanelThongKe);
        jPanelThongKe.setLayout(jPanelThongKeLayout);
        jPanelThongKeLayout.setHorizontalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongKeLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongKeLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addGap(76, 76, 76)
                        .addGroup(jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jSpinnerDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addGap(118, 118, 118))
        );
        jPanelThongKeLayout.setVerticalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addGroup(jPanelThongKeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Từ điển");
        setPreferredSize(new java.awt.Dimension(900, 500));
        setSize(new java.awt.Dimension(690, 439));

        jTextAreaHienThiTu.setColumns(20);
        jTextAreaHienThiTu.setRows(5);
        jScrollPane1.setViewportView(jTextAreaHienThiTu);

        jListDSTu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListDSTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDSTuMouseClicked(evt);
            }
        });
        jScrollPaneDSTu.setViewportView(jListDSTu);

        jTabbedPaneTraCuu.addTab("Tra cứu", jScrollPaneDSTu);

        jListDSYeuThich.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListDSYeuThich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDSYeuThichMouseClicked(evt);
            }
        });
        jScrollPaneDSYeuThich.setViewportView(jListDSYeuThich);

        jTabbedPaneTraCuu.addTab("Yêu thích", jScrollPaneDSYeuThich);

        jButtonDoiNgonNgu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDoiNgonNgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoiNgonNguActionPerformed(evt);
            }
        });

        jLabelLang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLang.setText("Anh - Việt");

        jTextFieldTraCuu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTraCuuKeyReleased(evt);
            }
        });

        jButtonThemYeuThich.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonThemYeuThich.setPreferredSize(new java.awt.Dimension(33, 33));
        jButtonThemYeuThich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemYeuThichActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Anh Việt");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Việt Anh");

        javax.swing.GroupLayout jPanelManHinhChinhLayout = new javax.swing.GroupLayout(jPanelManHinhChinh);
        jPanelManHinhChinh.setLayout(jPanelManHinhChinhLayout);
        jPanelManHinhChinhLayout.setHorizontalGroup(
            jPanelManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManHinhChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneTraCuu, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonThemYeuThich, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDoiNgonNgu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelManHinhChinhLayout.createSequentialGroup()
                        .addComponent(jLabelLang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTraCuu))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanelManHinhChinhLayout.setVerticalGroup(
            jPanelManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManHinhChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelManHinhChinhLayout.createSequentialGroup()
                        .addGroup(jPanelManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLang)
                            .addComponent(jTextFieldTraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelManHinhChinhLayout.createSequentialGroup()
                                .addComponent(jButtonThemYeuThich, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDoiNgonNgu, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane1)))
                    .addComponent(jTabbedPaneTraCuu))
                .addGap(18, 18, 18))
        );

        jMenuTuyChon.setText("Tùy chọn");

        jMenuItemTraCuu.setText("Màn hình tra cứu");
        jMenuItemTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraCuuActionPerformed(evt);
            }
        });
        jMenuTuyChon.add(jMenuItemTraCuu);

        jMenuItemThongKe.setText("Màn hình thống kê");
        jMenuItemThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThongKeActionPerformed(evt);
            }
        });
        jMenuTuyChon.add(jMenuItemThongKe);
        jMenuTuyChon.add(jSeparator1);

        jMenuItemThoat.setText("Thoát");
        jMenuItemThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThoatActionPerformed(evt);
            }
        });
        jMenuTuyChon.add(jMenuItemThoat);

        jMenuBar1.add(jMenuTuyChon);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelManHinhChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelManHinhChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDoiNgonNguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoiNgonNguActionPerformed
        // TODO add your handling code here:
        dict.chuyenDoiNgonNgu();
        loadManHinhChinh();
    }//GEN-LAST:event_jButtonDoiNgonNguActionPerformed

    private void jListDSTuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDSTuMouseClicked
        // TODO add your handling code here:
        try {
            String wordKey = jListDSTu.getSelectedValue();
            Word word = dict.traCuuTuChinhXac(wordKey);
            jTextAreaHienThiTu.setText(word.getMeaning());
        }
        catch(Exception e)  {   
            
        }
    }//GEN-LAST:event_jListDSTuMouseClicked

    private void jListDSYeuThichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDSYeuThichMouseClicked
        // TODO add your handling code here:
        String wordKey = jListDSYeuThich.getSelectedValue();
        Word word = dict.traCuuTuChinhXac(wordKey);
        jTextAreaHienThiTu.setText(word.getMeaning());
    }//GEN-LAST:event_jListDSYeuThichMouseClicked

    private void jTextFieldTraCuuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTraCuuKeyReleased
        // TODO add your handling code here:
        loadManHinhChinh();
    }//GEN-LAST:event_jTextFieldTraCuuKeyReleased

    private void jButtonThemYeuThichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemYeuThichActionPerformed
        // TODO add your handling code here:
        if(!jListDSTu.isSelectionEmpty()) {
            String wordKey = jListDSTu.getSelectedValue();
            String info = dict.luuLaiTuYeuThich(wordKey);
            loadDSYeuThich();
            if(info.contains("thanh cong")) {
                JOptionPane.showMessageDialog(this, "Đã lưu từ vào danh sách yêu thích");
            }
            if(info.contains("ton tai")) {
                JOptionPane.showMessageDialog(this, "Từ đã tồn tại trong danh sách yêu thích");
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn từ");
    }//GEN-LAST:event_jButtonThemYeuThichActionPerformed

    private void jMenuItemTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraCuuActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jPanelManHinhChinh);
        this.revalidate();
        this.loadManHinhChinh();
        
    }//GEN-LAST:event_jMenuItemTraCuuActionPerformed

    private void jMenuItemThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThongKeActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jPanelThongKe);
        this.revalidate();
        this.loadManHinhThongKe();
    }//GEN-LAST:event_jMenuItemThongKeActionPerformed

    private void jMenuItemThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThoatActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_jMenuItemThoatActionPerformed

    private void jSpinnerDate1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerDate1StateChanged
        // TODO add your handling code here:
        loadManHinhThongKe();
    }//GEN-LAST:event_jSpinnerDate1StateChanged

    private void jSpinnerDate2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerDate2StateChanged
        // TODO add your handling code here:
        loadManHinhThongKe();
    }//GEN-LAST:event_jSpinnerDate2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DictionaryForm form = new DictionaryForm();
                form.setVisible(true);
                form.loadManHinhChinh();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDoiNgonNgu;
    private javax.swing.JButton jButtonThemYeuThich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelLang;
    private javax.swing.JList<String> jListDSTu;
    private javax.swing.JList<String> jListDSYeuThich;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemThoat;
    private javax.swing.JMenuItem jMenuItemThongKe;
    private javax.swing.JMenuItem jMenuItemTraCuu;
    private javax.swing.JMenu jMenuTuyChon;
    private javax.swing.JPanel jPanelManHinhChinh;
    private javax.swing.JPanel jPanelThongKe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneDSTu;
    private javax.swing.JScrollPane jScrollPaneDSYeuThich;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSpinner jSpinnerDate1;
    private javax.swing.JSpinner jSpinnerDate2;
    private javax.swing.JTabbedPane jTabbedPaneTraCuu;
    private javax.swing.JTable jTableThongKe;
    private javax.swing.JTextArea jTextAreaHienThiTu;
    private javax.swing.JTextField jTextFieldTraCuu;
    // End of variables declaration//GEN-END:variables

    public void loadManHinhChinh() {
        loadDSTu();
        loadDSYeuThich();
        doiTenTuDien();
        resizeIcon(jButtonThemYeuThich);
        resizeIcon2(jButtonDoiNgonNgu);
    }
    
    public void loadManHinhThongKe() {
        loadBangThongKe();
    }

    //load toi da 100 tu
    private void loadDSTu() {
        DefaultListModel<String> model = new DefaultListModel<>();
        List<String> list = dict.traCuuTu(jTextFieldTraCuu.getText());
        Collections.sort(list);
        for(int i=0;i<MAX_WORDS && i<list.size();i++) {
            model.addElement(list.get(i));
        }
        jListDSTu.setModel(model);
        jScrollPaneDSTu.setViewportView(jListDSTu);
        
    }

    //load toi da 100 tu
    private void loadDSYeuThich() {
        DefaultListModel<String> model = new DefaultListModel<>();
        List<String> list = dict.dsTuYeuThich();
        Collections.sort(list);
        for(int i=0;i<MAX_WORDS && i<list.size();i++) {
            model.addElement(list.get(i));
        }
        jListDSYeuThich.setModel(model);
        jScrollPaneDSYeuThich.setViewportView(jListDSYeuThich);
        
    }

    private void doiTenTuDien() {
        if(dict.isAnhViet()) {
            jLabelLang.setText("Anh - Việt");
            setTitle("Từ điển Anh - Việt");
        }
        else
        {
            jLabelLang.setText("Việt - Anh");
            setTitle("Từ điển Việt - Anh");
        }
        
    }

    private void loadBangThongKe() {
        HashMap<String,Integer> dsThongKe = dict.thongKeTanSuatTraCuu(getDate((Date)jSpinnerDate1.getValue()), 
                                                                getDate((Date)jSpinnerDate2.getValue()));
        
        DefaultTableModel model = (DefaultTableModel)jTableThongKe.getModel();
        while(model.getRowCount() != 0) {
            model.removeRow(0);
        }
        Set set = dsThongKe.entrySet();
        // Lay mot iterator
        Iterator i = set.iterator();
        // Hien thi cac phan tu
        while(i.hasNext()) {
            Map.Entry me = (Map.Entry)i.next();
            String tu = (String)me.getKey();
            Integer times = (Integer) me.getValue();
            Vector row = new Vector();
            row.add(tu);
            row.add(times);
            model.addRow(row);
        }
        jTableThongKe.setModel( model);
        jPanelThongKe.revalidate();
       
    }
    
    private GregorianCalendar getDate(Date date) {
        GregorianCalendar calendar = new GregorianCalendar();
        //DateFormat sdf = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
        calendar.setTime(date);
        return calendar;
    }
    
    private void resizeIcon(JButton a) {
        ImageIcon ii = new ImageIcon(getClass().getResource("/images/star.png"));
        a.setIcon(new ImageIcon(ii.getImage().getScaledInstance(40, 40,
            java.awt.Image.SCALE_SMOOTH)));
    }
    
    private void resizeIcon2(JButton a) {
        ImageIcon ii = new ImageIcon(getClass().getResource("/images/way.png"));
        int height = a.getHeight();
        a.setIcon(new ImageIcon(ii.getImage().getScaledInstance(30, 120,
            java.awt.Image.SCALE_SMOOTH)));
    }
}
